# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      ctpUrl: "http://104.42.225.105/em"
      ctpUsername: 'admin'
      ctpPassword: 'admin'
      system: 'ParaBank'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Dynamically set MY_DATE environment variable
        run: echo "buildId=Parabank-$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Deploy Environment
        # You may pin to the exact commit or the version.
        # uses: parasoft/deploy-environment-action@ea4c180723d6eb7858e41fa89c2af734ddd8c8b5
        uses: parasoft/deploy-environment-action@1.0.0
        with:
          # CTP URL
          ctpUrl: '${{env.ctpUrl}}'
          # CTP Username
          ctpUsername: '${{env.ctpUsername}}'
          # CTP Password
          ctpPassword: '${{env.ctpPassword}}'
          # Name of the system
          system: '${{env.system}}'
          # Name of the environment
          environment: 'Golden'
          # Name of the environment instance to provision
          instance: 'Negative'
          # Fail action and abort on provisioning failure
          abortOnFailure: 'true'
          # Virtual assets in the environment will be replicated on another server
          copyToVirtualize: 'true'
          # The environment assets will be copied to a Virtualize server matching this name
          virtServerName: 'AzureVirtServer'
          # The name for the replicated environment can be used to later destroy the environment
          newEnvironmentName: 'NewFromAction-${{env.buildId}}'
      - name: Execute Job
        # You may pin to the exact commit or the version.
        # uses: parasoft/execute-job-action@4ff52dfe0b1abb285d1e94418d9b6015bbb5f6bc
        uses: parasoft/execute-job-action@1.0.0
        with:
          # CTP URL
          ctpUrl: '${{env.ctpUrl}}'
          # CTP Username
          ctpUsername: '${{env.ctpUsername}}'
          # CTP Password
          ctpPassword: '${{env.ctpPassword}}'
          # CTP Test Execution Job Name
          ctpJob: 'Status Job'
          # Abort the job after timeout exceeded
          abortOnTimeout: 'true'
          # Timeout value in minutes
          timeoutInMinutes: '15'
          # Publish test execution results to DTP
          publishReport: 'false'
          # DTP URL
          dtpUrl: 'http://54.149.98.67:8080'
          # DTP Username
          dtpUsername: 'user'
          # DTP Password
          dtpPassword: 'password'
          # DTP Project Name
          dtpProject: 'Parabank-v3'
          # Build ID to send to DTP
          buildId: '${{env.buildId}}'
          # Session Tag to send to DTP
          sessionTag: 'Github-Action-Session'
          # Append the test variable set environment name to the session tag
          appendEnvironment: 'true'
      - name: Destroy Environment
        # You may pin to the exact commit or the version.
        # uses: parasoft/destroy-environment-action@d24cf544b41f8454976fb79aadf3c78352e45c4f
        uses: parasoft/destroy-environment-action@1.0.0
        with:
          # CTP URL
          ctpUrl: '${{env.ctpUrl}}'
          # CTP Username
          ctpUsername: '${{env.ctpUsername}}'
          # CTP Password
          ctpPassword: '${{env.ctpPassword}}'
          # Name of the system
          system: '${{env.system}}'
          # Name of the environment
          environment: 'NewFromAction-${{env.buildId}}'
      - name: Disconnect Action
        # You may pin to the exact commit or the version.
        # uses: parasoft/disconnect-server-action@c07b9be852bd7309ab6b840d77e6bd4f079cb082
        uses: parasoft/disconnect-server-action@1.0.0
        with:
          # CTP URL
          ctpUrl: '${{env.ctpUrl}}'
          # CTP Username
          ctpUsername: '${{env.ctpUsername}}'
          # CTP Password
          ctpPassword: '${{env.ctpPassword}}'
          # Used to specify server by host or name
          serverMatch: 'name'
          # Host or name of the server
          server: 'nitrogen.parasoft.com'
